/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nisu;

import javax.sound.sampled.LineUnavailableException;
import java.awt.*;

public class App {
    public static void main(String[] args) throws LineUnavailableException, AWTException, InterruptedException {
        final JavaSoundRecorder recorder = new JavaSoundRecorder();
        recorder.start();
    }
}
